services:
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    template.service:
        class: FrontBundle\Service\TemplateService
        arguments: ["@service_container"]